/**
 * Sample payloads for testing transformations
 */

/** Default ISO 20022 pacs.008 sample payload */
export const DEFAULT_PAYLOAD = `<?xml version="1.0" encoding="UTF-8"?>
<Envelope>
  <AppHdr>
    <Fr>
      <FIId>
        <FinInstnId>
          <BICFI>ABWOBMQ1</BICFI>
        </FinInstnId>
      </FIId>
    </Fr>
    <To>
      <FIId>
        <FinInstnId>
          <BICFI>AAEEKNR1</BICFI>
        </FinInstnId>
      </FIId>
    </To>
    <BizMsgIdr>CBP3714749933</BizMsgIdr>
    <MsgDefIdr>pacs.008.001.08</MsgDefIdr>
    <BizSvc>swift.cbprplus.01</BizSvc>
    <CreDt>2026-01-27T06:38:25+00:00</CreDt>
    <PssblDplct>false</PssblDplct>
    <Rltd>
      <Fr>
        <FIId>
          <FinInstnId>
            <BICFI>ABWOBMQ1</BICFI>
          </FinInstnId>
        </FIId>
      </Fr>
      <To>
        <FIId>
          <FinInstnId>
            <BICFI>AAEEKNR1</BICFI>
          </FinInstnId>
        </FIId>
      </To>
      <BizMsgIdr>CBP3714749933</BizMsgIdr>
      <MsgDefIdr>pacs.008.001.08</MsgDefIdr>
      <CreDt>2026-01-27T06:38:25+00:00</CreDt>
    </Rltd>
  </AppHdr>
  <Document>
    <FIToFICstmrCdtTrf>
      <GrpHdr>
        <MsgId>CBP3714749933</MsgId>
        <CreDtTm>9999-12-31T00:00:00+00:00</CreDtTm>
        <NbOfTxs>1</NbOfTxs>
        <SttlmInf>
          <SttlmMtd>INDA</SttlmMtd>
        </SttlmInf>
      </GrpHdr>
      <CdtTrfTxInf>
        <PmtId>
          <InstrId>CBP3714749933</InstrId>
          <EndToEndId>NOTPROVIDED</EndToEndId>
          <TxId>bd314a71-93c3-43cc-81d4-59348f8966cf</TxId>
          <UETR>bd314a71-93c3-43cc-81d4-59348f8966cf</UETR>
        </PmtId>
        <PmtTpInf>
          <ClrChanl>BOOK</ClrChanl>
        </PmtTpInf>
        <IntrBkSttlmAmt Ccy="USD">291572383</IntrBkSttlmAmt>
        <IntrBkSttlmDt>2026-01-27</IntrBkSttlmDt>
        <ChrgBr>SHAR</ChrgBr>
        <InstgAgt>
          <FinInstnId>
            <BICFI>ABWOBMQ1</BICFI>
          </FinInstnId>
        </InstgAgt>
        <InstdAgt>
          <FinInstnId>
            <BICFI>AAEEKNR1</BICFI>
          </FinInstnId>
        </InstdAgt>
        <IntrmyAgt1>
          <FinInstnId>
            <BICFI>RKSECYD1827</BICFI>
          </FinInstnId>
        </IntrmyAgt1>
        <Dbtr>
          <Nm>Barrows and Torphy LLC</Nm>
          <Id>
            <OrgId>
              <LEI>VG8HY6Z4MJQTK12F9M54</LEI>
            </OrgId>
          </Id>
        </Dbtr>
        <DbtrAcct>
          <Id>
            <Othr>
              <Id>NOTPROVIDED</Id>
            </Othr>
          </Id>
        </DbtrAcct>
        <DbtrAgt>
          <FinInstnId>
            <BICFI>ABWOBMQ1</BICFI>
          </FinInstnId>
        </DbtrAgt>
        <CdtrAgt>
          <FinInstnId>
            <BICFI>PEDAUYO1</BICFI>
          </FinInstnId>
        </CdtrAgt>
        <Cdtr>
          <Nm>Dickinson and Paucek Group</Nm>
          <Id>
            <OrgId>
              <LEI>PT1BGLNXCVJ1NNHFLX73</LEI>
            </OrgId>
          </Id>
        </Cdtr>
        <CdtrAcct>
          <Id>
            <Othr>
              <Id>/DE70905955728081917052</Id>
            </Othr>
          </Id>
        </CdtrAcct>
        <InstrForNxtAgt>
          <InstrInf/>
        </InstrForNxtAgt>
        <RmtInf>
          <Ustrd>/RFB/ut ipsa sed</Ustrd>
        </RmtInf>
      </CdtTrfTxInf>
    </FIToFICstmrCdtTrf>
  </Document>
</Envelope>`;
